# Generated by Django 4.2.16 on 2024-10-23 14:39

import django.core.validators
from django.db import migrations, models
import transcriptDataExtractor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No Title', max_length=255)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), transcriptDataExtractor.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('assets', models.TextField(editable=False)),
                ('expenditures', models.TextField(editable=False)),
                ('income', models.TextField(editable=False)),
            ],
        ),
    ]
